# to run: docker compose -f docker/dev/docker-compose.yml up -d --build
services:
  inventory-frontend:
    build:
      context: ../../client
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ../../client:/app
      - /app/node_modules
    depends_on:
      keycloak-auth:
        condition: service_healthy
      inventory-backend:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
      NEXT_PUBLIC_KEYCLOAK_URL: http://localhost:7080
      NEXT_PUBLIC_KEYCLOAK_AUTH_URL: http://localhost-auth:7080/realms/inventory-realm/account
      NEXT_PUBLIC_KEYCLOAK_REALM: inventory-realm
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: inventory-frontend
      PUBLIC_KEYCLOAK_USER: vladimircuriel@outlook.com
      PUBLIC_KEYCLOAK_PASSWORD: vladimir
      PUBLIC_KEYCLOAK_USER_NO_ROLE: user@gmail.com
      PUBLIC_KEYCLOAK_PASSWORD_NO_ROLE: user
      NEXT_KEYCLOAK_REALM_BACKEND: inventory-backend
      NEXT_KEYCLOAK_LOGIN_ID: http://localhost:7080/realms/inventory-realm/protocol/openid-connect/auth?client_id=inventory-frontend&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&state=f0bf7df6-303e-4398-af50-0b6a566cba77&response_mode=fragment&response_type=code&scope=openid&nonce=8fc417cb-f39f-4e11-ab78-e45217d6a7df&code_challenge=jM6XGojdokuccskDzkeDM0R3sYRGtjIvntofAr48LwU&code_challenge_method=S256

  inventory-backend:
    build:
      context: ../../server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ../../server:/app
    environment:
      SPRING_APPLICATION_NAME: inventory-backend
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory-db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_AUTH_CONVERTER_RESOURCE_ID: inventory-backend
      JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE: preferred_username
      JWT_AUTH_CONVERTER_JWT_ISSUER_URI: http://localhost:7080/realms/inventory-realm
      JWT_AUTH_CONVERTER_JWT_JWK_SET_URI: http://localhost:7080/realms/inventory-realm/protocol/openid-connect/certs
      SPRING_HIBERNATE_ENVERS_ENABLED: true
      SPRING_HIBERNATE_ENVERS_AUDIT_TABLE_SUFFIX: _logs
      SPRING_HIBERNATE_ENVERS_STORE_DATA_AT_DELETE: true
      SPRING_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
      SPRING_MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: when-authorized
      SPRING_MANAGEMENT_METRICS_TAGS_APPLICATION: fuji-inventory
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      keycloak-auth:
        condition: service_healthy
      inventory-db:
        condition: service_healthy

  inventory-db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d inventory-db'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@inventory-db:5432/inventory-db?sslmode=disable"
    depends_on:
      inventory-db:
        condition: service_healthy
    ports:
     - "9187:9187"

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      inventory-db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--timeout=5", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../../grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      prometheus:
        condition: service_started
      postgres-exporter:
        condition: service_started

  keycloak-auth:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    volumes:
      - keycloak_dev_data:/opt/keycloak/data
      - ../../keycloak/inventory-realm-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "7080:7080"
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: http://localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "7080", "--import-realm" ]

volumes:
  keycloak_dev_data:
