api.base.url=${API_BASE_URL}
spring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

jwt.auth.converter.resource-id=${JWT_AUTH_CONVERTER_RESOURCE_ID}
jwt.auth.converter.principal-attribute=${JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE}

# spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_AUTH_CONVERTER_JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_AUTH_CONVERTER_JWT_JWK_SET_URI}
keycloak.auth-server.token-url=${KEYCLOAK_AUTH_SERVER_TOKEN_URL}

spring.jpa.properties.org.hibernate.envers.enabled=${SPRING_HIBERNATE_ENVERS_ENABLED}
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=${SPRING_HIBERNATE_ENVERS_AUDIT_TABLE_SUFFIX}
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=${SPRING_HIBERNATE_ENVERS_STORE_DATA_AT_DELETE}

management.endpoints.web.exposure.include=${SPRING_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
management.endpoint.health.show-details=${SPRING_MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}
management.metrics.tags.application=${SPRING_MANAGEMENT_METRICS_TAGS_APPLICATION}