spring.application.name=server-test

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.auth.converter.resource-id=${JWT_AUTH_CONVERTER_RESOURCE_ID}
jwt.auth.converter.principal-attribute=${JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_AUTH_CONVERTER_JWT_JWK_SET_URI}
keycloak.auth-server.token-url=${KEYCLOAK_AUTH_SERVER_TOKEN_URL}

spring.jpa.properties.org.hibernate.envers.enabled=true
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_logs
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=fuji-inventory