FROM gradle:8.14-jdk-21-and-24-corretto AS dev

WORKDIR /app

EXPOSE 8080

CMD ["gradle", "bootRun", "--no-daemon"]

# TODO: Make task to run cucumber/junit tests in gradle
FROM dev AS test
RUN gradle clean test cucumber --no-daemon