export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;

export const NEXT_KEYCLOAK_URL = process.env.NEXT_PUBLIC_KEYCLOAK_URL;

export const NEXT_KEYCLOAK_AUTH_URL = process.env.NEXT_PUBLIC_KEYCLOAK_AUTH_URL;

export const NEXT_KEYCLOAK_REALM = process.env.NEXT_PUBLIC_KEYCLOAK_REALM;

export const NEXT_KEYCLOAK_CLIENT_ID =
	process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID;

export const NEXT_PUBLIC_KEYCLOAK_REALM_BACKEND =
	process.env.NEXT_PUBLIC_KEYCLOAK_REALM_BACKEND ?? 'inventory-backend';
